[package]
name = "atomic"
version = "0.1.0"
authors = ["nolvalue"]
edition = "2018"

[dependencies]
#Basic Webserver Stuff
rocket = "0.4.5"

# Serialization/Deserialization
serde_json = "1.0.53"
serde = "1.0.110"
serde_derive = "1.0.110"

#Database
diesel = { version = "1.4.4", features = ["postgres"] }
rust-argon2 = "0.8.2"

#RNG
rand = '0.7.3'

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "diesel_postgres_pool"]
